# packages.sh — Install packages: core | interactive + optional plugins

REPO_ROOT_PACKAGES="${REPO_ROOT_PACKAGES:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
PACKAGES_DIR="$REPO_ROOT_PACKAGES/packages"

gzmo_normalize_package() {
  local raw="${1:-core}"
  raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]')"
  case "$raw" in
    core|interactive) echo "$raw" ;;
    minimal|standard|full|heartbeat)
      echo "install: profile '$raw' is deprecated — using 'core' (see docs/PACKAGES.md)" >&2
      echo "core"
      ;;
    *)
      echo "install: unknown profile '$raw' — using 'core'" >&2
      echo "core"
      ;;
  esac
}

gzmo_normalize_plugins() {
  local raw="${1:-}"
  local out="" id
  [[ -n "$raw" ]] || { echo ""; return 0; }
  for id in $(echo "$raw" | tr ',' ' '); do
    id="$(echo "$id" | tr '[:upper:]' '[:lower:]' | tr -d ' ')"
    [[ -n "$id" ]] || continue
    if [[ -f "$PACKAGES_DIR/plugins/${id}.env" ]]; then
      out="${out:+$out,}$id"
    else
      echo "packages: unknown plugin '$id' (no packages/plugins/${id}.env)" >&2
    fi
  done
  echo "$out"
}

gzmo_merge_plugin_bundles() {
  local env_file="$1"
  local plugins_csv="${2:-}"
  [[ -n "$plugins_csv" ]] || return 0
  local id
  for id in $(echo "$plugins_csv" | tr ',' ' '); do
    id="$(echo "$id" | tr '[:upper:]' '[:lower:]' | tr -d ' ')"
    [[ -n "$id" ]] || continue
    local pb="$PACKAGES_DIR/plugins/${id}.env"
    if [[ -f "$pb" ]]; then
      {
        echo ""
        echo "# --- plugin: $id ---"
        cat "$pb"
      } >>"$env_file"
    fi
  done
}

gzmo_merge_env_bundles() {
  local env_file="$1"
  local package="${2:-core}"
  local with_api="${3:-0}"
  local api_token="${4:-}"
  local plugins_csv="${5:-}"

  package="$(gzmo_normalize_package "$package")"

  local core_bundle="$PACKAGES_DIR/core/.env.bundle"
  [[ -f "$core_bundle" ]] || { echo "packages: missing $core_bundle" >&2; return 1; }

  {
    echo ""
    echo "# --- package: core ---"
    cat "$core_bundle"
  } >>"$env_file"

  if [[ "$package" == "interactive" ]]; then
    local ibundle="$PACKAGES_DIR/interactive/.env.bundle"
    [[ -f "$ibundle" ]] || return 1
    {
      echo ""
      echo "# --- package: interactive ---"
      cat "$ibundle"
    } >>"$env_file"
  fi

  plugins_csv="$(gzmo_normalize_plugins "$plugins_csv")"
  gzmo_merge_plugin_bundles "$env_file" "$plugins_csv"

  if (( with_api == 1 )); then
    local addon
    addon="$(gzmo_addon_path api)"
    [[ -f "$addon" ]] || return 1
    {
      echo ""
      echo "# --- addon: api ---"
      grep -v '^#' "$addon" | grep -v '^[[:space:]]*$' || true
    } >>"$env_file"
    if [[ -n "$api_token" ]]; then
      printf 'GZMO_API_TOKEN="%s"\n' "$api_token" >>"$env_file"
    fi
  fi
}

gzmo_addon_path() {
  echo "$PACKAGES_DIR/addons/${1}.env"
}

gzmo_write_installer_env() {
  local env_file="$1"
  local package="$2"
  local vault_path="$3"
  local ollama_url="$4"
  local ollama_model="$5"
  local dropzone_dir="$6"
  local with_api="${7:-0}"
  local api_token="${8:-}"
  local plugins_csv="${9:-}"

  package="$(gzmo_normalize_package "$package")"
  plugins_csv="$(gzmo_normalize_plugins "$plugins_csv")"

  cat >"$env_file" <<EOF
# Generated by GZMO installer — package: $package
VAULT_PATH="$vault_path"
OLLAMA_URL="$ollama_url"
OLLAMA_MODEL="$ollama_model"
GZMO_DROPZONE_DIR="$dropzone_dir"
GZMO_PROFILE=core
GZMO_PLUGINS="${plugins_csv}"

EOF

  gzmo_merge_env_bundles "$env_file" "$package" "$with_api" "$api_token" "$plugins_csv"
}
